In [1]:
import numpy as np

houses = np.array([
    [100, 3, 200],
    [150, 4, 300],
    [200, 5, 400],
    [120, 3, 250]
])

print("Dataset:")
print(houses)

Dataset:
[[100   3 200]
 [150   4 300]
 [200   5 400]
 [120   3 250]]


In [2]:
X = houses[:, :-1]
print("\nFeatures (X):")
print(X)


Features (X):
[[100   3]
 [150   4]
 [200   5]
 [120   3]]


In [3]:
y = houses[:, -1]
print("\nTarget (y):")
print(y)


Target (y):
[200 300 400 250]
