In [1]:
import numpy as np
houses = np.array([
    [1200, 3, 200000],
    [1500, 4, 250000],
    [1000, 2, 150000],
    [1800, 4, 300000]
])

print("Dataset:")
print(houses)

Dataset:
[[  1200      3 200000]
 [  1500      4 250000]
 [  1000      2 150000]
 [  1800      4 300000]]


In [2]:
x = houses[:, :-1]
print("Features (X):")
print(x)

Features (X):
[[1200    3]
 [1500    4]
 [1000    2]
 [1800    4]]


In [3]:
y = houses[:, -1]
print("Target (y):")
print(y)

Target (y):
[200000 250000 150000 300000]


In [4]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print("Original shape:", numbers.shape)

column = numbers.reshape(-1, 1)

print("Reshaped:")
print(column)
print("New shape:", column.shape)


Original shape: (4,)
Reshaped:
[[10]
 [20]
 [30]
 [40]]
New shape: (4, 1)
